services:
  net-creator:
    image: busybox
    command: ["sh", "-c", "docker network create rabbitmq_go_net || true"]
    networks:
      - rabbitmq_go_net

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    depends_on:
      - net-creator
    networks:
      - rabbitmq_go_net

  order-db:
    extends:
      file: ./OrderManagement/compose.yaml
      service: order-db

  order-app:
    extends:
      file: ./OrderManagement/compose.yaml
      service: order-app

  product-db:
    extends:
      file: ./Product/compose.yaml
      service: product-db

  delivery-db:
    extends:
      file: ./Delivery/compose.yaml
      service: delivery-db

  product-app:
    extends:
      file: ./Product/compose.yaml
      service: product-app

  client-db:
    extends:
      file: ./Client/compose.yaml
      service: client-db

  client-app:
    extends:
      file: ./Client/compose.yaml
      service: client-app

  delivery-app:
    extends:
      file: ./Delivery/compose.yaml
      service: delivery-app


networks:
  product-network:
    name: product-network
  order-network:
    name: order-network
  client-network:
    name: client-network
  delivery-network:
    name: delivery-network
  rabbitmq_go_net:
    name: rabbitmq_go_net
