services:

  order-db:
    container_name: postgres-order
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - ./data/db/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=order_database
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=myuser
      - TZ=America/Sao_Paulo
    ports:
      - "5432:5432"
    networks:
      - order-network

  order-app:
    container_name: java-order
    image: maven:3.8.4-openjdk-17
    volumes:
      - ./:/app
    working_dir: /app
    command: bash -c "mvn clean install && java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -jar target/OrderManagement.jar"
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - "8080:8080"
      - "5005:5005"
    networks:
      - order-network
    depends_on:
      - order-db

networks:
  order-network:
    name: order-network