version: '3.8'

services:
  product-db:
    container_name: postgres-product
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - ./data/db/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=product_database
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=myuser
      - TZ=America/Sao_Paulo
    ports:
      - "5433:5432"
    networks:
      - product-network

  product-app:
    container_name: java-product
    image: maven:3.8.4-openjdk-17
    volumes:
      - ./:/app
    working_dir: /app
    command: bash -c "mvn clean install && cp target/Product.jar /app/Product.jar && java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -jar /app/Product.jar"
    environment:
      - TZ=America/Sao_Paulo
      - SPRING_RABBITMQ_HOST=rabbitmq
    ports:
      - "8081:8080"
      - "5006:5005"
    networks:
      - product-network
      - rabbitmq_go_net
    depends_on:
      - product-db

networks:
  rabbitmq_go_net:
    external: true
  product-network:
    name: product-network
