services:

  delivery-db:
    container_name: delivery-postgres
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - ./data/db/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=delivery
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=myuser
      - TZ=America/Sao_Paulo
    ports:
      - "5436:5432"
    networks:
      - delivery-network

  delivery-app:
    container_name: delivery-java
    image: maven:3.8.4-openjdk-17
    volumes:
      - ./:/app
    working_dir: /app
    command: bash -c "mvn clean install && java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -jar target/Delivery.jar"
    environment:
      - TZ=America/Sao_Paulo
      - SPRING_RABBITMQ_HOST=rabbitmq  # Aqui estamos utilizando o nome do contêiner RabbitMQ
    ports:
      - "8086:8080"
      - "5008:5005"
    networks:
      - delivery-network
      - rabbitmq_go_net
    depends_on:
      - delivery-db

networks:
  rabbitmq_go_net:
    external: true
  delivery-network:
    name: delivery-network